/*
 * Prelude — lib/prelude.scala, embedded in the binary (PreludeSource.cpp is
 * generated by CMake) and compiled into every session before user code.
 */
#pragma once
#include "compiler/BytecodeModule.h"
#include "compiler/GlobalTable.h"

#include <memory>
#include <vector>

namespace proto { class ProtoContext; }

namespace protoScala {

class ExecutionEngine;

const char* preludeSource();

// Per-stage wall time of the last loadPrelude call, in microseconds. Filled
// unconditionally (five clock reads per process start, no allocation) and
// printed when PROTOSCALA_PRELUDE_TIMING is set to a non-empty value. Phase 6
// Task 1 uses it to attribute the cold-start miss of DESIGN §1; Task 2 uses it
// to prove the prelude image removed what it claims to remove.
struct PreludeTiming {
    double parseUs = 0.0;    // parseSource
    double desugarUs = 0.0;  // desugar
    double compileUs = 0.0;  // Compiler::compileUnit (or buildPreludeImage)
    double linkUs = 0.0;     // BytecodeModule::linkSymbols
    double runUs = 0.0;      // ExecutionEngine::run (MAKE_CLASS, MAKE_FN, STORE_GLOBAL, ...)
    double totalUs = 0.0;
    bool fromImage = false;  // the precompiled image path was taken
};
const PreludeTiming& preludeTiming();

/**
 * Which prelude path this BINARY will take, answered by the library rather than by
 * a macro in the caller.
 *
 * Why it exists: `--version` used to test `PROTOSCALA_HAVE_PRELUDE_IMAGE` in
 * `src/main.cpp`. That macro is `PUBLIC` on the `protoscala_runtime` OBJECT library,
 * and once Phase 7 made `protoscala` link the shared `protoScala` target — which
 * links the object libraries PRIVATE — it stopped reaching `main.cpp`. The binary
 * kept using the image and `--version` started reporting that it did not, which is
 * the worst shape of defect for a `--version`: the thing a user checks, quietly
 * wrong. Asking the library removes the class of bug, because the answer now comes
 * from a translation unit compiled with the definition, by construction.
 */
enum class PreludePath {
    Source,            // this build has no image (cross-compiled, or the tool absent)
    Image,             // an image is present and valid, and will be used
    ImageDisabled,     // an image is present and valid, but PROTOSCALA_PRELUDE_NO_IMAGE is set
    ImageStale,        // an image is present but its format or source hash does not match
};
PreludePath preludePath();

// Parses, compiles and runs the prelude under `parent`: its definitions join
// `globals`, its modules `modules` (retained for the session). Throws
// std::logic_error when the prelude fails — a build defect, never user input.
void loadPrelude(proto::ProtoContext* parent, ExecutionEngine& engine, GlobalTable& globals,
                 std::vector<std::unique_ptr<BytecodeModule>>& modules);

} // namespace protoScala
