/*
 * Prelude — lib/prelude.scala, embedded in the binary (PreludeSource.cpp is
 * generated by CMake) and compiled into every session before user code.
 */
#pragma once
#include "compiler/BytecodeModule.h"
#include "compiler/GlobalTable.h"

#include <memory>
#include <vector>

namespace proto { class ProtoContext; }

namespace protoScala {

class ExecutionEngine;

const char* preludeSource();

// Parses, compiles and runs the prelude under `parent`: its definitions join
// `globals`, its modules `modules` (retained for the session). Throws
// std::logic_error when the prelude fails — a build defect, never user input.
void loadPrelude(proto::ProtoContext* parent, ExecutionEngine& engine, GlobalTable& globals,
                 std::vector<std::unique_ptr<BytecodeModule>>& modules);

} // namespace protoScala
